///////////////////////////////////////////////////////////////////////////////
// MyCppProjectClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "MyCppProjectClassFactory.h"
#include "MyCppProjectServices.h"
#include "MyCppProjectVersion.h"
#include "CyclicIO.h"

BEGIN_CLASS_MAP(CMyCppProjectClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_MyCppProject, CID_MyCppProjectCCyclicIO, SRVNAME_MYCPPPROJECT "!CCyclicIO", CCyclicIO)
///</AutoGeneratedContent>
END_CLASS_MAP()

CMyCppProjectClassFactory::CMyCppProjectClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_MYCPPPROJECT));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(MyCppProject));
#endif //defined(TCDBG_UNIT_VERSION)
}

