///////////////////////////////////////////////////////////////////////////////
// MyCppProjectInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "MyCppProjectServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
