///////////////////////////////////////////////////////////////////////////////
// MyCppProjectServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_MyCppProject = 0x3F000000;
#define SRVNAME_MYCPPPROJECT "MyCppProject"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_MyCppProjectCCyclicIO = {0x481d65af,0x7ae1,0x4a43,{0xb8,0x57,0x7a,0xf9,0x11,0xc7,0xad,0x8e}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_CyclicIOParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _CyclicIOParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} CyclicIOParameter, *PCyclicIOParameter;

typedef struct _CyclicIOInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} CyclicIOInputs, *PCyclicIOInputs;

typedef struct _CyclicIOOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} CyclicIOOutputs, *PCyclicIOOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_CyclicIOInputs 0
#define ADI_CyclicIOOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
